# La version du langage dans le fichier est obsolète maintenant
# version: '3.8'

services:
  # Renommé pour cohérence
  mysql:
    image: mysql:8.0
    # Par défaut les conteneurs seront nommés : repertoire_services_NUM
    # Les nommer à la main avec un nom différent du service peut porter à confusion
    # container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: formulaire_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    # Je change les ports car chez moi j'ai des trucs qui tournent sur ces ports
    # Tu pourras changer à nouveau
    ports:
      - "3366:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - my_network
    restart: unless-stopped

  php:
    build: .
    # Idem
    # container_name: my_php
    # Idem pour les ports
    ports:
      - "8008:80"
    volumes:
      - ./site_login:/var/www/html
    environment:
      # Ici c'est ok... on peut utiliser le nom de service pour nommer une machine
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: formulaire_db
    networks:
      - my_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: my_phpmyadmin
    environment:
      PMA_HOST: mysql
      #PMA_USER: user
      #PMA_PASSWORD: password
      PMA_PORT: 3306
    ports:
      - "8009:80"
    depends_on:
      - mysql
    networks:
      - my_network
    restart: unless-stopped

volumes:
  db_data:

networks:
  my_network:
    driver: bridge